baseurl = "/"
languageCode = "en-us"
title = "Abiola Ibrahim"
theme = "casper"
paginate = 10
DisqusShortname = "abiosoft"
Copyright = "All rights reserved - 2020"

[params]
  subtitle = "Software Craftsman"
  cover = "images/cover.png"
  author = "Abiola Ibrahim"
  bio = "Technically adventurous with a mix of geek, gamer and coder"
  googleAnalyticsUserID = "UA-70866902-1"
  email = "a@abiosoft.com"
  twitter = "//twitter.com/abiosoft"
  facebook = "//facebook.com/abiosoft"
  github = "//github.com/abiosoft"
  linkedin = "//ng.linkedin.com/in/abiosoft"
  hobbies = "coding in Go, coding in Typescript, coding with Vim, toying with Caddy, building with Containers"
  hobbytext = "I like"
[permalinks]
  post = "/:slug/"
